version: "2"
services:
  webserver: 
    container_name: webserver
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ../mysite:/usr/share/nginx/html
    expose: 
      - "80"
    ports: 
      - "80:80"